### PR TITLE
Create prototype demo page

### PR DESCRIPTION
**Pull request by pengyuejiang**
Hello! I created a simple demo page just to check if this works? Please give suggestions! And there seems to be some bug about the plugin somehow… YouTube, Wikipedia and Reddit links disappear and the thumbnails are not behaving properly.

### CODE REVIEW

**Comment by mdolr** [comment]
Hello, I don't know what OneMeal (page title?) is but I feel like you've used code that is already copyrighted, regarding the nature of this repository and its license I can not take the risk of merging code that is probably copyrighted. Also you might want to configure your git to stop it from comitting DS_store files.

This pull request won't be merged, thank you nonetheless, you might want to check other issues if you really want to contribute.

**Comment by pengyuejiang** [comment]
That's actually from my previous repositories, I assembled my old codes a bit

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mdolr** [comment]
Oh okay then no problem

**Review by mdolr — APPROVED** [review]
will remove DS_Store + fix page title

**Pull request merged**
