### PR TITLE
Added  player for channels

### PR DESCRIPTION
**Pull request by egfanboy**
This will call the youtube iframe API with the channel. It will display the latest upload of the channel on hover of the link

### CODE REVIEW

**Review by mdolr — COMMENTED** [review]
The PR is great however having a video player when you hover a channel might confuse people so I'll keep the PR on hold for now but it will likely be merged once I find a way (either via metadata/ or API) to make a clean youtube channel profile (channel name / videos count? subcount? etc)

**Review by mdolr — APPROVED** [review]

**Comment by egfanboy** [comment]
wasn't sure if you wanted to include querying the youtube API for channel info. If so I can add that in and create an element with that info. However that requires that you have a API token

**Comment by mdolr** [comment]
I'm trying to think of a workaround, querying the page's metadata is one of the solution which could be implemented easily

**Comment by egfanboy** [comment]
I tried loading the actual channel page in an iframe and then getting the info from that but its blocked since it needs to be on the same origin

**Comment by mdolr** [comment]
Hum even without using an iframe wouldn't the metadata be available through a simple fetch call ?
Maybe we could rely on a lib like https://github.com/mozilla/page-metadata-parser

**Comment by egfanboy** [comment]
Problem I am encountering is that we are blocked by CORS to make a fetch call to the channel and parse the DOM

**Comment by mdolr** [comment]
CORS shouldn't be a problem because we're injecting the scripts as content script, I've had no problem so far when fetching within the elements so far.

**Pull request closed without merging**
