### PR TITLE
Setting to disable self-referenced links

### PR DESCRIPTION
**Pull request by grubdragon**
Implemented functionality to disable links which reference the current domain itself.
Tries to tackle issue #120 partially.
TODO: Extend to ship with a blacklist

### CODE REVIEW

**Comment by mdolr** [comment]
I thought about it a bit, maybe we could make things way simpler, by just letting people input websites in a comma separated list rather than hardcoding domains and having a switch for each one, what do you think of this ?

**Comment by grubdragon** [comment]
The only problem with the switches is that it'll call for too many additional switches.
Letting people input a list and add to it domain filtering, and it'll probably work out well. Just thinking about where this input would be located. In the small popup it could be a bit irritating to type.

**Comment by mdolr** [comment]
We might want to move all of the global settings to a settings page which would make things easier I think

EDIT: I just merged #129 we will now use the onboarding page as a settings page

**Review by mdolr — APPROVED** [review]

**Comment by grubdragon** [comment]
Hey! seems like you did the needful. Thanks, I just came into a ton of work, so have been busy.

**Pull request merged**
