### PR TITLE
Added dark mode

### LINKED ISSUE #73: Add support for dark mode
Add the possibility to switch the survol div to dark mode.

Tasks :
* Add a setting in the settings popup to toggle dark mode
* Change the CSS to have a dark mode maybe using css variables ?

### PR DESCRIPTION
**Pull request by dmb1107**
* I've added a toggle for dark mode that changes the CSS variables _fg-color_ and _bg-color_ (defined in _base.css_)
* Note: I wasn't able to figure out how to make the changes apply without a page refresh. I think it should be an easy fix for someone more knowledgable to do.

### CODE REVIEW

**Comment by mdolr** [comment]
I’ll look into this later, I guess to apply the changes without reloading the page we could use the chrome internal messaging system to communicate between the popup and the core. I can take care of that

**Comment by plushugh** [comment]
@mdolr could use a media query and use system/browser dark mode settings.

**Comment by mdolr** [comment]
Hum, I'm testing this right now
* Dark theme is only applied to the popup (settings page) and does not affect the survol container
* From my poor CSS understanding I think you're trying (in `core.js`) to affect the page body, which we should not interact with, we should limit ourselves to changing the survol container.

Also @plushugh what do you mean exactly ?

**Comment by plushugh** [comment]
> Hum, I'm testing this right now
> 
> * Dark theme is only applied to the popup (settings page) and does not affect the survol container
> 
> * From my poor CSS understanding I think you're trying (in `core.js`) to affect the page body, which we should not interact with, we should limit ourselves to changing the survol container.
> 
> 
> 
> Also @plushugh what do you mean exactly ?

[https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by mdolr** [comment]
Oh didn't know about this, we should use it then, however that doesn't solve the problems I've listed already.

**Comment by dmb1107** [comment]
> Hum, I'm testing this right now
> 
> * Dark theme is only applied to the popup (settings page) and does not affect the survol container
> * From my poor CSS understanding I think you're trying (in `core.js`) to affect the page body, which we should not interact with, we should limit ourselves to changing the survol container.
> 

* The dark theme is applied to the survol container but only after you reload the page after toggling it.
* In `core.js` I only changed the CSS variabels which are used in the survol containers, not the page body.

**Comment by mdolr** [comment]
isn't `document.documentElement.style.setProperty('--bg-color--', '#212121');` [here](https://github.com/mdolr/survol/pull/74/files#diff-d85c7ecdc144ac4aec3ee7a0b24c3f9fR208) affecting the document's body ? (If some site had exactly the same variable names for example?)  

Also do you really have the container working in dark theme ? Because I've tested it before-after reloading, tried every scenario and I couldn't get it to work, it applies to the popup but it doesn't apply to the survol container (at least for me). If you could take a screenshot that would be nice :+1:

**Comment by dmb1107** [comment]
> isn't `document.documentElement.style.setProperty('--bg-color--', '#212121');` [here](https://github.com/mdolr/survol/pull/74/files#diff-d85c7ecdc144ac4aec3ee7a0b24c3f9fR208) affecting the document's body ? (If some site had exactly the same variable names for example?)
> 
> Also do you really have the container working in dark theme ? Because I've tested it before-after reloading, tried every scenario and I couldn't get it to work, it applies to the popup but it doesn't apply to the survol container (at least for me). If you could take a screenshot that would be nice 👍

* I see what you mean, that definitely would be a problem.
* I just tried running it on my Mac with Chrome and dark mode did not work.

I'm sorry for the confusion, I think it's best that you scrap my PR and let another person have a go at it.

Edit: I just tested on my machine that I developed it on and it's no longer working. I think I had it working at some point and had some CSS cached that made it still in dark mode.

**Comment by mdolr** [comment]
It's fine don't worry. I'm not sure everything should be removed.
I'll try to see if I can work on this during the weekend, I know @KeshriAyushi22 wanted to work on that maybe he has an idea on how to implement it.

**Pull request closed without merging**
