### PR TITLE
fixed the youtube link in twitter and added the start button to start…

### PR DESCRIPTION
**Pull request by issamoxix**
… the extension
gith
added the twitter youtube thing and start button for the extension 
im interested in this project

### CODE REVIEW

**Comment by issamoxix** [comment]
git2
subscribers Number

**Review by mdolr — CHANGES_REQUESTED** [review]
Hello, 

Thank you for your PR implementing (#10) however it needs more work, here is a list of things to change :
* Please don't push your `console.log` it's fine to add some if you need to test things but remove them before pushing (`js/core.js` and `js/background/auxiliary.js`)
* As you're adding a youtube feature please work with the appropriated integration (`js/templates/youtube.js`) the `js/templates/base.js` file should only be used when sites are not officially implemented
* I'm not sure what you tried to do with this whole popup thing, the extension shouldn't need a button to start it should run automatically. We however need a popup to change settings like disabling the extension on certain websites, or have a switch to toggle the preview of every site using base.js. This should be done in a separate PR and it should adress #40

**Comment by issamoxix** [comment]
I add the start button because the extension starts before the page load.
I will add that thing on youtube.js file (that was my bad ) 
I forgot to remove the console.log (my bad too )

**Comment by mdolr** [comment]
ok I think I get what you mean by the extension starts before the page loads, you've only tested this on twitter I believe and twitter loads content asynchronously, an issue was opened #54 and has been fixed by #57. The exntesion shouldn't need a manual input to start itself.

**Pull request closed without merging**
