### PR TITLE
Added badge to extension icon

### LINKED ISSUE #130: Add a badge on the extension icon
To make it more clear whether the extension is enabled or not, and to show people that the icon is click-able, a badge should be added. It should display ON/OFF depending on the state of the extension on the page. 

Just like Adblock plus or Ublock use a badge to display the amount of ads blocked on a page

### PR DESCRIPTION
**Pull request by katyasichov**
Fixes https://github.com/mdolr/survol/issues/130. Badge added to the extension icon.

### CODE REVIEW

**Comment by mdolr** [comment]
You've added this in the popup's script, this should be situated in `js/core.js`

**Comment by katyasichov** [comment]
Thank you for feedback. I'll make the changes.

**Comment by katyasichov** [comment]
I changed the logic. I put the code in core.js and add event listener to chrome.storage. The badge is activated in auxiliary when the content script sends a message. The reason for this : chrome.browserAction.setBadgeText can only be executed in the background file. Let me know if additional changes are needed. Thank you

**Review by mdolr — APPROVED** [review]
:+1: Good job, thank you for your contribution

**Pull request merged**
