### PR TITLE
[Issue#115] : add onboarding page when extension is first installed

### PR DESCRIPTION
**Pull request by ask-imran**
This PR is part of [issue#115](https://github.com/mdolr/survol/issues/115) 

Changes made:
- add a new onboarding page when the extension is installed the first time
- refactor the code to add `bootsrap.js` to have common functionalities which can used by both popup and onboarding

Things to further improve (This could be on a separate PR) :
- add values in other locales for newly added string
- The popup & onboarding have JS duplicated, this could be overcome by adding a bootstrap for popup and utilizing the `bootstrap.js`
- The common CSS could be extracted into its own file
- add git changelogs
- remove `Enable Survol on this page` from onboarding page ✅

Survol-Extension-OnboardingPage

### CODE REVIEW

**Comment by mdolr** [comment]
Thank you for your PR

I've changed some things, trying to make the onboarding page look like the popup. Also I removed the "enable on survol on this page" parameter as it doesn't make any sense here.

I'm unsure about the gif idea honestly. I think we should use something else. Also maybe we could add a way to show the changelog using the Git releases feed ?

**Comment by ask-imran** [comment]
> I'm unsure about the gif idea honestly. I think we should use something else. Also maybe we could add a way to show the changelog using the Git releases feed ?

Let me know if you have other thoughts around, I can remove the gif. I kind of looks gigantic now. I'll look at the git releases feed

**Comment by ask-imran** [comment]
Hey @mdolr,
I had some look around the git release, I feel we could use github api for the latest release instead of the [feeds](https://github.com/mdolr/survol/releases.atom).

Let me know your thoughts

**Comment by ask-imran** [comment]
Added github release note, exclude prerelease check, display last release

image

**Comment by mdolr** [comment]
Great changes, I'm waiting for #131 which adds a new setting and then I'll be able to merge this

**Review by mdolr — APPROVED** [review]

**Pull request merged**
